### ISSUE TITLE
弃项

### ISSUE THREAD

**Issue by zhangjh** [zhangjh/-HTML-#3]
To 雷子:
不指望你能继续学了，你这三分钟热度的我也领教过多次了。。
你的问题之一在于，想法总比行动多。兴趣来得快去的更快。
我不能总是催促你，于是弃项好了。很遗憾，没能一起完成这个项目。

**Comment by ytlds2003** [comment]
，，我天天加班到9点多才走，，老师能不能有点耐心，，
